import Head from 'next/head';

export default function Contact({ test }: { test: string }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Remote Page contact</h1>
        {`getServerSideProps - ${test}`}
      </main>
    </>
  );
}

export async function getServerSideProps() {
  return {
    props: {
      test: 'BBBB'
    }
  };
}
